# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 494)
        MainWindow.setStyleSheet("#MainWindow{background:black;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background:black;}")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 691, 421))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.captured = QtWidgets.QLabel(self.groupBox)
        self.captured.setGeometry(QtCore.QRect(20, 30, 361, 271))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.captured.setFont(font)
        self.captured.setAutoFillBackground(False)
        self.captured.setStyleSheet("#captured{\n"
" background-color: lightgray;\n"
"}")
        self.captured.setText("")
        self.captured.setObjectName("captured")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 161, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_file_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.choose_file_2.setFont(font)
        self.choose_file_2.setStyleSheet("#choose_file_2{\n"
"background: white;\n"
"\n"
"}")
        self.choose_file_2.setObjectName("choose_file_2")
        self.verticalLayout.addWidget(self.choose_file_2)
        self.pose_extracte_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.pose_extracte_2.setFont(font)
        self.pose_extracte_2.setStyleSheet("#pose_extracte_2{\n"
"background:lightgreen;\n"
"}")
        self.pose_extracte_2.setObjectName("pose_extracte_2")
        self.verticalLayout.addWidget(self.pose_extracte_2)
        self.play_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.play_2.setFont(font)
        self.play_2.setStyleSheet("#play_2{\n"
"background:lightblue;\n"
"}")
        self.play_2.setObjectName("play_2")
        self.verticalLayout.addWidget(self.play_2)
        self.predict_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.predict_2.setFont(font)
        self.predict_2.setStyleSheet("#predict_2{\n"
"background:lightgreen;\n"
"}")
        self.predict_2.setObjectName("predict_2")
        self.verticalLayout.addWidget(self.predict_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 317, 181, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pose = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.pose.setFont(font)
        self.pose.setStyleSheet("#pose{color:white;}")
        self.pose.setObjectName("pose")
        self.verticalLayout_2.addWidget(self.pose)
        self.rgb_pose = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.rgb_pose.setFont(font)
        self.rgb_pose.setStyleSheet("#rgb_pose{color:white;}")
        self.rgb_pose.setObjectName("rgb_pose")
        self.verticalLayout_2.addWidget(self.rgb_pose)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("#label{color:white;}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.prediction_result_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.prediction_result_2.setFont(font)
        self.prediction_result_2.setStyleSheet("#prediction_result_2{\n"
"background:lightgray;\n"
"font-size:15px;\n"
"}")
        self.prediction_result_2.setText("")
        self.prediction_result_2.setObjectName("prediction_result_2")
        self.verticalLayout_2.addWidget(self.prediction_result_2)
        self.opened = QtWidgets.QLabel(self.groupBox)
        self.opened.setGeometry(QtCore.QRect(390, 0, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.opened.setFont(font)
        self.opened.setStyleSheet("#opened{color:white;}")
        self.opened.setObjectName("opened")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_file_2.setText(_translate("MainWindow", "Choose File/Files"))
        self.pose_extracte_2.setText(_translate("MainWindow", "Pose Estimation Extraction "))
        self.play_2.setText(_translate("MainWindow", "Play"))
        self.predict_2.setText(_translate("MainWindow", "Predict"))
        self.pose.setText(_translate("MainWindow", "only sekelton"))
        self.rgb_pose.setText(_translate("MainWindow", "RGB with pose "))
        self.label.setText(_translate("MainWindow", "Result"))
        self.opened.setText(_translate("MainWindow", "Openned Video List "))
